In [23]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 25.0.1 -> 26.1.1
[notice] To update, run: pip install --upgrade pip

In [5]:
!python --version

Python 3.12.9

In [1]:
import pandas as pd
import os
import seaborn as sns
import matplotlib.pyplot as plt
pd.options.mode.chained_assignment = None
sns.set_theme()

In [ ]:
train = pd.read_csv("train.csv")
len(train.filename.unique())

In [ ]:
test = pd.read_csv("test.csv")
len(test.filename.unique())

In [ ]:
test.head()

In [ ]:
def isValid(*dirs):
    return os.path.isfile(os.path.join(os.getcwd(),*dirs))
train['valid_path'] = [isValid('data','imagenes',filename) for filename in train.filename]
train.valid_path.value_counts()

In [ ]:
test['valid_path'] = [isValid('data','imagenes',filename) for filename in test.filename]
test.valid_path.value_counts()

In [ ]:
data_total = pd.concat([train,test]).reset_index(drop=True)
data_total.to_csv("etiquetas.csv", header=True, index_label=False, index = False)
sns.histplot(data = data_total, y = "class")
plt.tight_layout()

In [ ]:
data_total['valid_path'] = [isValid("data","imagenes",filename) for filename in data_total.filename]
data_total.valid_path.value_counts()

## Chequeo de imagenes y etiquetas

In [ ]:
import shutil
def make_compress_folders_from_labels(dta:pd.DataFrame,column:str,make_dirs = True,compress_dirs = False):
    for label in dta[column].unique():
        if  label == None:
            label = 'Borrado'
        if make_dirs & (not os.path.exists(os.path.join(os.getcwd(), label))):
            os.makedirs(os.path.join(os.getcwd(), label))
        if compress_dirs:
            shutil.make_archive(f"{label}", "zip", os.path.join(os.getcwd(), f"{label}"))

In [14]:
import numpy as np

def bbox_COCO_format(bbox:list[float])->list[float]:
    x_center = 0.5 * (bbox[0] + bbox[2])
    y_center = 0.5 * (bbox[1] + bbox[3])
    width = np.abs(bbox[2] - bbox[0])
    height = np.abs(bbox[3] - bbox[1])
    return [x_center,y_center,width,height]

In [9]:
def bbox_de_COCO_format(bbox:list[float])->list[float]:
    x_min = bbox[0] - (0.5 * bbox[2])
    y_min = bbox[1] - (0.5 * bbox[3])
    x_max = x_min + bbox[2]
    y_max = y_min + bbox[3]
    return x_min,y_min,x_max,y_max

In [14]:
from PIL import Image,ImageDraw,ImageFont
from tqdm import tqdm
def take_labels_out(data:pd.DataFrame,column:str=None,report_name:str=''):
    enriching_list = []
    # os.makedirs()
    for name in tqdm(data.filename.unique(),total = len(data.filename.unique())):
        image_file = Image.open(os.path.join('/Volumes/ADATA HD680/Shared/Files From d.localized/Maestria/tesis/herbario/data_MELU/train/images',name))
        image_df = data.loc[data.filename == name]
        image_df['Numero de etiquetas diferentes en la imagen'] = image_df.shape[0]
        #image_df['Numero de clases de etiquetas diferentes en la imagen'] = len(image_df[column].unique())
        image_df['duplicamiento de etiqueta en x'] = image_df['xmax'].duplicated(keep=False) & image_df['xmin'].duplicated(keep=False)
        image_df['duplicamiento de etiqueta en y'] = image_df['ymax'].duplicated(keep=False) & image_df['ymin'].duplicated(keep=False)
        # if 'Mascara_Encabezados' in image_df['class'].unique() : #len(image_df['class'].unique()) < 6:
        # image_df['name_with_position'] = ''
        image_df['name_of_picture'] = ''
        # print(image_df.reset_index())
        image_df = image_df.reset_index(drop = True)
        for i,row in image_df.iterrows():
            # print(i)
            #if row[column] == None:
            #    row[column] = 'Borrado'
            #image_df['name_of_picture'][i] = f'{name[:-4]}_{row[column]}_{i}.jpg'
            # image_df['name_with_position'][i] = f'{name[:-4]}_{row["class"]}_{(row["xmin"],row["ymin"],row["xmax"],row["ymax"])}_{i}.jpg'
            draw_row = ImageDraw.Draw(image_file)
            
            width = image_file.width
            height = image_file.height

            # --- YOLO center format conversion (cx, cy, w, h) → corner coords ---
       

            # Clamp to [0, 1]
        
            xmin , ymin, xmax, ymax = bbox_de_COCO_format([row["xmax"], row["ymax"], row["xmin"], row["ymin"]])
            print(xmin,ymin,xmax,ymax)
            
            # xmin = max(0.0, min(1.0, row["xmin"])) 
            # ymin = max(0.0, min(1.0, row["ymin"]))
            # xmax = max(0.0, min(1.0, row["xmax"]))
            # ymax = max(0.0, min(1.0, row["ymax"]))

            # # # Scale to pixel coordinates
            xmin = int(round(xmin * width))
            ymin = int(round(ymin * height))
            xmax = int(round(xmax * width))
            ymax = int(round(ymax * height))

            # # Safety swap if somehow still inverted
            if xmin > xmax:
                xmin, xmax = xmax, xmin
            if ymin > ymax:
                ymin, ymax = ymax, ymin

            draw_row.rectangle((xmin, ymin, xmax, ymax), outline=(250, 0, 0))
            image_file.show()
            label_mask = image_file.crop((xmin, ymin, xmax, ymax))
            label_mask.save(os.path.join(os.getcwd(),f'{row["class_name"]}_{i}.jpg'),format="JPEG", quality=90)
            # image_file.save(os.path.join(os.getcwd(),'label_data', f'{name[:-4]}_highligted.jpg'), format="JPEG", quality=90)
        # print(name)
        
        # image_file.show()
        enriching_list.append(image_df)
    data_total_enrich = pd.concat(enriching_list).reset_index(drop = True)   


# print(data_total_enrich.mean(numeric_only=True).to_frame())
    cols_to_select = data_total_enrich.drop(['xmin','xmax','ymin','ymax'], axis=1).columns
    statistic_analisis = data_total_enrich[cols_to_select].describe()

    with pd.ExcelWriter(f"analisis_descriptivo_{report_name}.xlsx") as writer:
        data_total_enrich.to_excel(writer, sheet_name="base enriquecida")  
        statistic_analisis.to_excel(writer, sheet_name="estadistica descriptiva")

## Entendiendo de la revision

In [ ]:
import pandas as pd
from PIL import Image
import time
import os
from tqdm import tqdm

In [ ]:
datos_a_cambiar = pd.read_excel("Revision imgs.xlsx")
datos_a_cambiar = datos_a_cambiar.rename(columns = {'Carpeta':'Label_Actual','Donde deberia estar':'Label_Deseado'})

In [ ]:

datos_a_cambiar['folder'] = datos_a_cambiar.Imagen.str.split('_')
datos_a_cambiar['folder'] = datos_a_cambiar['folder'].apply(lambda x: f'{x[1]}_{x[2]}')
# datos_a_cambiar['revisado'] = False
a_revisar = []
for i,row in tqdm(datos_a_cambiar.iterrows(),total=datos_a_cambiar.shape[0]):
    # print(type(row))
    # if not row['revisado']: #row['Label_Deseado'] not in datos_a_cambiar.Label_Actual.unique():
    read_path = os.path.join(os.getcwd(),row.folder,f'{row.Imagen}.jpg')
    if not os.path.isfile(read_path):
        print(row.to_frame().transpose())
        a_revisar.append(row.to_frame().transpose())
    else:
        imagen_tmp = Image.open(read_path)
        # print(row['Label_Actual'],row['Label_Deseado'])
        if row['Label_Deseado'] == '?':
            row['Label_Deseado'] = 'Desconocido'
        save_folder = os.path.join(os.getcwd(),f'{row["Label_Actual"]}_covertir_a_{row["Label_Deseado"]}')
        if not os.path.exists(save_folder):
            os.makedirs(save_folder)
        imagen_tmp.save(os.path.join(save_folder,f"{row['Imagen']}.jpg"),format="JPEG", quality=90)
            # datos_a_cambiar['revisado'][i] = True
        # time.sleep(5)
direcciones_anomalas = pd.concat(a_revisar)
direcciones_anomalas.to_csv('archivos_nombres_equivocados.csv',index = False)

## Chequeando por archivos faltantes

In [ ]:
import os
import pandas as pd
from thefuzz import fuzz

In [ ]:
def find_file(start_path, target_file):
    for root, dirs, files in os.walk(start_path):
        if target_file in files:
            return ['encontrado',{os.path.join(root, target_file)}]
        else:
            for file_name in files:
                partial_ratio = fuzz.partial_ratio(target_file, file_name)
                if (partial_ratio >= 97) & (partial_ratio < 100)  :
                    return ['coincidencia parcial encontrada', {os.path.join(root, file_name)}]
    return ['archivo no encontrado',None]

In [ ]:
archivos_anomalos = pd.read_csv("archivos_nombres_equivocados.csv")
archivos_anomalos['status'] = archivos_anomalos['Imagen'].apply(lambda x: find_file(os.getcwd(),x)[0])
archivos_anomalos['location'] = archivos_anomalos['Imagen'].apply(lambda x: find_file(os.getcwd(),x)[1])
archivos_anomalos.to_csv('archivos_nombres_equivocados_buscados.csv')

In [ ]:
archivo_original_etiquetas = pd.read_excel("analisis_descriptivo_etiquetas.xlsx",sheet_name= 'base enriquecida')

In [4]:
melu_files_path = os.path.join('/Users/juanpablovargasacosta/herbario' , 'labels_databases', 'etiquetas_melu.csv')

In [5]:
df_melu = pd.read_csv(melu_files_path)

df_melu.head()

,class_name,filename,width,height,xmax,ymax,xmin,ymin
0,number,MELUA000209a_sp61255492538133088657_medium.png,801,1200,0.721979,0.320033,0.039039,0.017917
1,institutional label,MELUA000209a_sp61255492538133088657_medium.png,801,1200,0.755730,0.883883,0.439451,0.181400
2,handwritten data,MELUA000209a_sp61255492538133088657_medium.png,801,1200,0.464813,0.542787,0.369251,0.031075
3,database label,MELUA000209a_sp61255492538133088657_medium.png,801,1200,0.813215,0.758150,0.315968,0.069217
4,swatch,MELUA000209a_sp61255492538133088657_medium.png,801,1200,0.369220,0.878754,0.205206,0.198908

In [6]:
df_melu = df_melu.drop_duplicates(subset=['class_name'], keep='first').reset_index(drop=True)

In [7]:
df_melu

,class_name,filename,width,height,xmax,ymax,xmin,ymin
0,number,MELUA000209a_sp61255492538133088657_medium.png,801,1200,0.721979,0.320033,0.039039,0.017917
1,institutional label,MELUA000209a_sp61255492538133088657_medium.png,801,1200,0.755730,0.883883,0.439451,0.181400
2,handwritten data,MELUA000209a_sp61255492538133088657_medium.png,801,1200,0.464813,0.542787,0.369251,0.031075
3,database label,MELUA000209a_sp61255492538133088657_medium.png,801,1200,0.813215,0.758150,0.315968,0.069217
4,swatch,MELUA000209a_sp61255492538133088657_medium.png,801,1200,0.369220,0.878754,0.205206,0.198908
5,scale,MELUA000209a_sp61255492538133088657_medium.png,801,1200,0.066866,0.564213,0.079900,0.311642
6,annotation label,MELUA000548a_sp69084138081882807155_medium.png,821,1200,0.150012,0.520304,0.276370,0.053742
7,small database label},MELUA001236a_sp66058582448494087539_medium.png,802,1200,0.875867,0.645850,0.182207,0.031050
8,full database label,MELUA002505a_sp64651282478728385927_medium.png,802,1200,0.805330,0.731779,0.339913,0.293375
9,stamp,MELUA002749a_sp62269462651438665609_medium.png,811,1200,0.782633,0.818000,0.421048,0.031617
10,swing tag,MELUD100307a_sp68614772036982365384_medium.png,798,1200,0.160689,0.644071,0.125965,0.115725

In [ ]:
archivo_original_etiquetas = archivo_original_etiquetas.rename(columns={'class':'old_class'})
archivo_original_etiquetas['new_class'] = archivo_original_etiquetas['old_class']
# archivo_original_etiquetas.head()

In [ ]:
def change_label_base_on_folder_structure(*address,delete = False):
    for root,dirs,files in os.walk(os.path.join(os.getcwd(),*address)):#'por_cambiar_etiquetas','Cambio_simple'
        for directory in dirs:
            for img in os.listdir(os.path.join(root,directory)):
                directory_info = directory.split('_')
                new_class = directory_info[-1] 
                if delete:
                    new_class = None
                img_info = img.split('_')
                archivo_original_etiquetas.loc[(archivo_original_etiquetas.filename == f'{img_info[0]}.png') & (archivo_original_etiquetas.name_of_picture == img),'new_class'] = new_class
            # print(img.split('_'))
        # print(os.listdir(os.path.join(root,directory)),directory)

In [ ]:
change_label_base_on_folder_structure('por_cambiar_etiquetas','Cambio_simple')
change_label_base_on_folder_structure('por_cambiar_etiquetas','borrar',delete=True)

In [ ]:
archivo_original_etiquetas.loc[archivo_original_etiquetas.name_of_picture == 'COL000001500_Mascara_Descripciones_1788.jpg']#head()

In [ ]:
archivo_original_etiquetas.loc[archivo_original_etiquetas.name_of_picture == 'COL000000745_Mascara_Descripciones_1744.jpg']

In [ ]:
archivo_original_etiquetas = archivo_original_etiquetas.drop(columns=['Unnamed: 0','valid_path','Numero de etiquetas diferentes en la imagen','Numero de clases de etiquetas diferentes en la imagen','duplicamiento de etiqueta en x','duplicamiento de etiqueta en y','name_with_position'])

In [ ]:
archivo_original_etiquetas.old_class = archivo_original_etiquetas.old_class.apply(lambda x: x.split('_')[-1])
archivo_original_etiquetas.new_class = archivo_original_etiquetas.new_class.apply(lambda x: x.split('_')[-1] if x != None else x)
archivo_original_etiquetas.to_csv("renombramiento_etiquetas.csv",index = False)#.head()

In [ ]:
make_compress_folders_from_labels(archivo_original_etiquetas,'new_class')

In [15]:
take_labels_out(df_melu,'','etiquetas_corregidas')

  0%|          | 0/6 [00:00<?, ?it/s]

0.7024595 0.31107450000000003 0.7414985000000001 0.32899150000000005
0.5360045 0.793183 0.9754555 0.974583
0.2801875 0.5272495 0.6494385 0.5583245
0.655231 0.7235415 0.971199 0.7927584999999999
0.266617 0.7793 0.471823 0.978208
0.026915999999999995 0.408392 0.106816 0.720034

 17%|█▋        | 1/6 [00:01<00:08,  1.67s/it]

0.011827000000000004 0.493433 0.28819700000000004 0.547175

 33%|███▎      | 2/6 [00:02<00:05,  1.37s/it]

0.7847635 0.630325 0.9669705 0.661375

 50%|█████     | 3/6 [00:03<00:02,  1.07it/s]

0.6353735 0.5850915 0.9752865000000001 0.8784665

 67%|██████▋   | 4/6 [00:03<00:01,  1.38it/s]

0.572109 0.8021915 0.993157 0.8338085

 83%|████████▎ | 5/6 [00:04<00:00,  1.66it/s]

0.0977065 0.5862084999999999 0.2236715 0.7019334999999999

100%|██████████| 6/6 [00:04<00:00,  1.36it/s]

In [ ]:
# jupyter nbconvert --to script understand_data.ipynb --output understanding_labels.py